services:
  http:
    container_name: $NAME
    image: rclone/rclone:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 88:88
    volumes:
      - ~:/files:ro
    user: 1000:1000
    environment:
      - TZ=Europe/London
    command: >
      serve http /files
        -v
        --addr 0.0.0.0:88
        --vfs-cache-mode off
networks: {}
