services:
  watchtower:
    container_name: $NAME
    image: containrrr/watchtower
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}
