services:
  twitchets:
    container_name: $NAME
    image: arranhs/twitchets:develop
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ~/twitchets:/twitchets
    environment:
      - DEBUG=true
networks: {}
