services:
  meilisearch:
    container_name: $NAME
    image: getmeili/meilisearch:v1.9
    restart: unless-stopped
    networks:
      - meilisearch
    volumes:
      - ~/meilisearch:/meili_data
    environment:
      - MEILI_MASTER_KEY=1234
networks:
  meilisearch:
    name: meilisearch
    driver: bridge